### ISSUE TITLE
Permission to write to the git

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/kcsrv#11]
Could I get permission to commit stuff to the repo? Unless you want me to do pull requests, then that's fine. Up to you.

**Comment by uppfinnarn** [comment]
I'd rather you do pull requests. Right now, the code you write is a mess and you're not particularly familiar with Python (you basically write PHP(4) with Python syntax) or Linux, so I'd rather you send me your contrubutions so I can help you improve.
