### ISSUE TITLE
After getting Core.swf, game stops loading (regression from issue #4?)

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/kcsrv#13]
Seems that I'm encountering the same issue as #4 . Regression?
In the chrome inspector, usually the game will start asking for other files (ie. the API endpoints). But after getting mainD2 and the Core SWF files (just Core.swf), communication stops.

However, I spotted that this line was malfunctioning in the play page template:
```{{ url_for('kcs', path='kcs/mainD2.swf', _external=True) }} ```

As it was then trying to pull the SWF from http://<my VM IP address>:5000/kcs/kcs/ instead of just one /kcs/ prefix. I changed it to this to make it more 'correct' but it didn't make any changes.
```{{ url_for('kcs', path='mainD2.swf', _external=True) }}```

The asset downloader that I coded and @SunDwarf adapted into the project is downloading the correct length files (filesizes match the ones provided here in the git project). So I don't think that's the problem, however I am using the Debian VM inside VMWare with NAT Network Card. Could that be an issue?

**Comment by SunDwarf** [comment]
Huh, works fine here. 
```
Remote Address:127.0.0.1:80
Request URL: http://127.0.0.1/kcs/Core.swf?version=cnhbdryxidwq
Request Method:GET
```

**Comment by SoftwareGuy** [comment]
How are you running the server? Are you proxying through Nginx to Flask or some other trickery?

If I set flask to port 80 I get permission denied unless I use sudo but that's just stupid.

**Comment by SoftwareGuy** [comment]
Okay, now with the latest commit "port.json" does not exist. I think the .gitignore is nerfing the JSON files (if one is set up).

**Comment by SunDwarf** [comment]
1) I run a ssh tunnel from 5000->80.
2) Port json is my own personal port, you need to provide your own dump.

**Comment by SoftwareGuy** [comment]
Alright.

I've broken my virtualenv (forgot to run bin/activate; instead I did virtualenv again which killed the python3 configuration for python2.7... >_<) so I'll try again tomorrow.

Still can't get why the game doesn't like port 5000. Maybe it's hardwired to only go on port 80? Although I swear when I was tinkering around I managed to get it booting on port 5000 before you took over the project.

**Comment by SunDwarf** [comment]
The swfs are probably hardcoded to use ip:80 or something, if they were decompilable itd 	beeasier

**Comment by SoftwareGuy** [comment]
I have a gut feeling you're on the money there. And since the SWF is getting "connection refused" it's going nowhere.

I'll try the SSH tunnel trick tomorrow when I've fixed my virtualenv. Keep you posted.

**Comment by uppfinnarn** [comment]
They're decompilable alright, at least they were last I checked.

What does [this line](https://github.com/KanColleTool/kcsrv/blob/master/modules/play/templates/play/index.html#L9) currently evaluate to? If that doesn't include a port, that could be why.

**Comment by SunDwarf** [comment]
Core.swf won't decompile nor decompress properly when I try

**Comment by uppfinnarn** [comment]
Oh right, that particular one is obfuscated on the server and deobfuscated in-memory by mainD2.swf, starting about a year ago.

If you can decompile the scripts from mainD2.swf, you should be able to deobfuscate it yourself without too much trouble. ActionScript is basically JavaScript with some extra syntax, so porting the deobfuscation code to NodeJS should be very easy.

**Comment by SoftwareGuy** [comment]
Confirmed. Running the SSH Tunnel from Port 5000 -> Localhost 80 allows the game to boot correctly.
So there we go - the game requires port 80. I'll add this info to my fork's readme and also do up a config for nginx.

**Comment by SunDwarf** [comment]
Since it's resolved, closing.
