### ISSUE TITLE
firstship API Endpoint - AssertError

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/kcsrv#17]
Possibly the last bug report before I log off tonight.

1. Make a new user (don't assign a new admiral in Admin panel to the account)
2. Boot the game using the new user account.
3. You'll get the tutorial, continue and pick ship.
4. Complete the garbage it spews at you, you'll get errorcat with [this backtrace](https://gist.github.com/SoftwareGuy/f6ea2ab4420a8255b5e3) that spits out "AssertError".

Server will create the admiral and set it up, but can't do anything else after that error.

**Comment by SunDwarf** [comment]
You haven't imported ships. Run manage.py update_db or so.

**Comment by SoftwareGuy** [comment]
Geez, I feel like a baka right now. Thanks.

Maybe the update_db part should get run at first bootup if the ships don't exist in the database? Something to consider.

**Comment by uppfinnarn** [comment]
That's a terrible idea, it'd add overhead to the startup, extra code to detect if ships are already imported or not (or up to date, even), and all this for a potentially data-clobbering operation at that.

**Comment by SoftwareGuy** [comment]
Alright, will test this out when I get to the office.

**Comment by SoftwareGuy** [comment]
First ship works now, however port2, the end point that the game polls after the tutorial completes, throws a not implemented (201) or wrong JSON returned. Other than that reloading the game will allow me to log in to my desk ready to do admiral tasks.

**Comment by uppfinnarn** [comment]
If you could capture a proper response to this somehow, that'd be a big help

**Comment by SunDwarf** [comment]
I believe I have a proper response for ship2 saved somewhere, but I don't want to have to implement it yet because it's not used ever except for certain querying somewhere that isn't even slightly implemented.

**Comment by SoftwareGuy** [comment]
I would have to make another DMM account. Doable, but would they connect the dots?
