### ISSUE TITLE
Vagrant up provisioning stops at "TASK: [create user database]"

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/kcsrv#2]
When bringing up the VM using Vagrant; The provisioning process gets stuck on the following:
`TASK: [create user database]`
This has been stuck for say an hour in the hopes it'll unstuck itself but to no avail. I could possibly go in and complete the database setup, but not 100% sure what state the setup is in.

VM Box used is trusty64, ubuntu14.04.1 amd64 from http://www.vagrantbox.es .

EDIT: Got it working, just finished the installation by hand. Everything is working as it should, although I had to change to /vagrant and do ./bin/python3 ./kcsrv.py (as I did all the other steps, including virtualenv . in /vargrant) and if I didn't do that, it would throw a "no module called flask" error.

I will most likely fork the repo or submit a pull request; I've made it slightly prettier with the official KC banner on the background (took me a while to figure out the templates) of the pages, and might just come along for the ride and get my head around how the api works.

EDIT 2: Gah, now I broke something again. Good job, SoftwareGuy >_>

**Comment by SoftwareGuy** [comment]
Been meaning to get back into the swing of working on this. Real life has been quite demanding. My PHP implementation is crude and really sucks balls, so I've forked this and going to try working on it. Although I do have Kirishima looking at me last time I logged in!

I'm going to need to study how the DB layer is done, because what I can do is create the needed ship girl and equipment tables. However, if you could, could you sometime tell me how the firepower and such is done in the game via DMM reverse engineering? I'm thinking the way of doing this is:

Shipgirl table has the girl with her attributes and such, the admiral she belongs to and her in-game ID along with a rowID identifer. 

Equipment has the rowID (autoincrement) and it's attributes, how much it boosts what stat.
When the game asks for girl equipment data, my implementation nulls all the attack/def/etc to 0, so they are "weak" because it's not implemented. 

What I'm thinking is we'd need to take the base value from the ship girl, then for each equipment ID which is not -1 (not equipped), fetch the buffs from the equipment table and then return the total value. I also figured out the buckets, devmats, and such being depleted when the game sends the buildship commands. All I'd need to do is convert it from PHP to Python...

So if you could, could you boot up KC sometime and build a el cheapo shipgirl, then strip her of her weaponry, note the values and then deck her out again and see if the values change? I suspect this is what the DMM api does... I'm even tempted to start a new DMM account just for reverse engineering.

Sidenote: Oh shit we're running on PostgreSQL and not MySQL...

**Comment by uppfinnarn** [comment]
Please do show me what you've got, especially of responses and the like. I have some decompiled ActionScript dumps you can have, but I think this information is documented elsewhere if you look around - given how SERIOUS BUSINESS ship min/maxing is, I'd be very surprised if it wasn't.

I don't play KanColle much anymore, but what it sounds like you're looking for is available in the big start2 database it downloads on. If you can get past the tutorial and into the actual game with your version, I'd be happy to port it back onto Python (and clean this codebase up a bit).

I'm probably more experienced with database layouts than you are, so I think it'd be easier if I did that part. I need responses to know how to get it out of there though!

**Comment by SoftwareGuy** [comment]
Sure. I'll zip up what I have and email you a MEGA link, I'll include all the character data and such that I've leeched. I have the start2 json file and PHP rejected it at first (hit the 1024 entry JSON decoder limit). I upped that to double that (2048) and I got it to spit back a preformatted var_dump(). It's /such/ a big clusterfuck, why use japanese field names when you could keep it english?!

My implementation will get you to the dashboard and building ships will work as in the server will take your buckets and then error cat on you. If you hack in any ship - I haven't tried boss girls but I've modded in Amatsukaze, Kongou and Kirishima. Nagato and Mutsu also worked. Ooyou crashed the game (I think she referenced some API calls I didn't plug with dummy 200 messages) but she did appear in the dashboard.

I was going to do a Unity3D take on KC but that fell flat. It was fun but then I looked at how KC implemented everything and was like *barf*.

Got any rough ideas on sorting out the RNG for shipgirl builds? Or should we just let people get a grab bag, if you do 30/30/30/30 and get a Musashi then you got lucky (ie. RNG between from 1 and the playable ship numbers)

**Comment by SoftwareGuy** [comment]
Email sent.

**Comment by SoftwareGuy** [comment]
Did you get the email or did Gmail block it for some reason?
