### ISSUE TITLE
Ship moving acts retardedly

### ISSUE THREAD

**Issue by SunDwarf** [KanColleTool/kcsrv#20]
Can somebody take a look at [this code](https://github.com/KanColleTool/kcsrv/blob/master/modules/user/user.py#L19) and tell me why it doesn't work properly

I'm tired and can't good code program

**Comment by SoftwareGuy** [comment]
Hate to ask but why close my issue and then reopen another? You could have just use my existing issue ticket (saves clutter)...

**Comment by SunDwarf** [comment]
Gonna close this, as this appears to have been fixed somewhere along the line.
