### ISSUE TITLE
Build Ship Logic - Ponderings

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/kcsrv#22]
While not an issue as such, maybe we could use it like a discussion topic.

Something that I don't quite get with DMM's official server logic - how are the ships we construct done on the server side? My theory is that regardless of amount of resources, you will always have in the base pool (for lack of better name) the destroyers. I've put a battleship recipe in and got a Fubuki. No kidding.

When you hit a certain threshold with the amount of resources required, for example the Battleship recipe, the server will add the BBs into the pool and any that are superseded by that resources amount (CAs, etc). Then, it's a matter of the lotto with the stars aligning at the right position and bingo, you have your ship.

Or have you masterminds already worked out the black magic DMM uses?

**Comment by SunDwarf** [comment]
That is basically it, yeah. I don't want to have a base pool in kcsrv unless you enter an invalid recipe, because RNG games are very rarely fun.

**Comment by uppfinnarn** [comment]
Let's just make everything craft Naka-chan 100% of the time and see if anyone notices.

**Comment by SunDwarf** [comment]
Naka is shit
100% 6th des div or die

**Comment by uppfinnarn** [comment]
NAKA-CHAN DAYO~

**Comment by SunDwarf** [comment]
time to blacklist naka and her sisters 		fromthedb

**Comment by SoftwareGuy** [comment]
Tenryuu and her kindergarten best fleet or your resources back
