### ISSUE TITLE
Game doesn't seem to load anymore.

### ISSUE THREAD

**Issue by SunDwarf** [KanColleTool/kcsrv#24]
It downloads core.swf successfully, but nothing happens after that.

Dunno when this happened.

**Comment by SunDwarf** [comment]
@SoftwareGuy you're my brilliant bug tester and nitpicker, can you reproduce this if possible?

**Comment by SunDwarf** [comment]
Nevermind I was running my connection on 127.0.0.1:5000, not just 127.0.0.1. Ignore me

**Comment by SoftwareGuy** [comment]
*points to the readme file*

**Comment by SunDwarf** [comment]
yes, yes, funny
