### ISSUE TITLE
Idea: server offers to generate a config salt if the user didn't set one up

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/kcsrv#25]
Just thought of this.

Why not, if the server detects someone didn't change the configuration file salts that it either a) throws an ascii art of Naka-chan and quits or b) asks the user if they want to let it make a random 16 - 32 character string?

I know this is promoting lazy "eh just download and lol oss kc server".

**Comment by SunDwarf** [comment]
I'll probably make it just print a "you are shit" error at somepoint.
