### ISSUE TITLE
500 HTTP Error

### ISSUE THREAD

**Issue by kdevproject** [KanColleTool/kcsrv#27]
I completed until the installation. kcsrv.py have also been running smoothly. However, I receive a much 500 http error. Please help me

**Comment by SunDwarf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On 19/09/15 15:24, kdevproject wrote:
> I completed until the installation. kcsrv.py have also been running smoothly. However, I receive a much 500 http error. Please help me
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/KanColleTool/kcsrv/issues/27>.
> 
Full traceback?
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iJ4EARMKAAYFAlX9ctYACgkQbojIu8gUUMZuuwH9Ef7JapRzaSEVGKReTP/QmuyZ
fUaKz2uyG9S4ZHLcioaIxWakfpHwGMBXOCYb3GMtcscmbIv+0wdV4tkubmTAGQH+
KJfiwKMQeIDvF4liEVJ7Lgpw3z9czk1tUzgO0CrsulmXlki8RClAPYjes5JLJ4tL
bOnzAdI50+g/hXcFamQo+A==
=B/fs
-----END PGP SIGNATURE-----

**Comment by kdevproject** [comment]
English is not good So please understand

When I executed kcsrv.py and I tried to accessing 0.0.0.0:5000, I got logs.

Warning: This is a debugging configuration. Run with the gunicorn script to run in production.
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [20/Sep/2015 22:42:15] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [20/Sep/2015 22:42:15] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Sep/2015 22:42:15] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [20/Sep/2015 22:42:21] "GET /play HTTP/1.1" 301 -
127.0.0.1 - - [20/Sep/2015 22:42:21] "GET /play/ HTTP/1.1" 302 -
127.0.0.1 - - [20/Sep/2015 22:42:21] "GET /account/login HTTP/1.1" 500 -
127.0.0.1 - - [20/Sep/2015 22:42:27] "GET /account HTTP/1.1" 404 -

I use Manjaro linux and Linux kernel version is 4.3 RC and I did not use the virtual machine. Clear the operating system is tried again. However, the same error is repeated.

**Comment by SunDwarf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512



On 20/09/15 14:59, kdevproject wrote:
> English is not good So please understand
> 
> When I executed kcsrv.py and I tried to accessing 0.0.0.0:5000, I got logs.
> 
> Warning: This is a debugging configuration. Run with the gunicorn script to run in production.
> 
>   * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit) 127.0.0.1 - - [20/Sep/2015 22:42:15] "GET / HTTP/1.1" 500 - 127.0.0.1 - - [20/Sep/2015 22:42:15] "GET /favicon.ico HTTP/1.1" 404 - 127.0.0.1 - - [20/Sep/2015 22:42:15] "GET /favicon.ico HTTP/1.1" 404 - 127.0.0.1 - - [20/Sep/2015 22:42:21] "GET /play HTTP/1.1" 301 - 127.0.0.1 - - [20/Sep/2015 22:42:21] "GET /play/ HTTP/1.1" 302 - 127.0.0.1 - - [20/Sep/2015 22:42:21] "GET /account/login HTTP/1.1" 500 - 127.0.0.1 - - [20/Sep/2015 22:42:27] "GET /account HTTP/1.1" 404 -
> 
> I use Manjaro linux and Linux kernel version is 4.3 RC and I did not use the virtual machine. Clear the operating system is tried again. However, the same error is repeated.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/KanColleTool/kcsrv/issues/27#issuecomment-141786638>.
> 
Thanks, can you go into your config.py file, add the line `DEBUG = True`, and run it again and paste the traceback again, please?
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iJ4EARMKAAYFAlX+wecACgkQbojIu8gUUMbfOQH/eKGU2jltqbUBEISSEgMaXltp
wp2dr6zcDExP4Wt1/PLw8kZk728Itdwyk1ERoo2KOine5NH4zw8o1IgyhPsdNAIA
qWvedPMw+Ufkkg/76uXsxgGRaDVTx4S0Y1guKUDvFN+hzfWJAo7zomXaScCH7Uqj
WJ3hOfDge1wE3gIsO/ODnw==
=Sv8h
-----END PGP SIGNATURE-----

**Comment by kdevproject** [comment]
Here's traceback :

```
Warning: This is a debugging configuration. Run with the gunicorn script to run in production.
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Warning: This is a debugging configuration. Run with the gunicorn script to run in production.
127.0.0.1 - - [20/Sep/2015 23:28:16] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/khmproject/kcsrv/init.py", line 55, in index
    return render_template('index.html')
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/khmproject/kcsrv/templates/index.html", line 2, in top-level template code
    {% include "layout/_navbar.html" %}
  File "/home/khmproject/kcsrv/templates/layout/_navbar.html", line 1, in top-level template code
    {% block navbar %}
  File "/home/khmproject/kcsrv/templates/layout/_navbar.html", line 21, in block "navbar"
    {% if not current_user.is_authenticated() %}
AttributeError: 'bool' object has no attribute '__call__'
127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /play/ HTTP/1.1" 302 -
127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask_security/decorators.py", line 203, in wrapper
    if current_user.is_authenticated():
TypeError: 'bool' object is not callable
127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 -
127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by SunDwarf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On 20/09/15 15:31, kdevproject wrote:
> Here's traceback :
> 
> |Warning: This is a debugging configuration. Run with the gunicorn script to run in production. * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit) * Restarting with stat Warning: This is a debugging configuration. Run with the gunicorn script to run in production. 127.0.0.1 - - [20/Sep/2015 23:28:16] "GET / HTTP/1.1" 500 - Traceback (most recent call last): File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__ return self.wsgi_app(environ, start_response) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app response = self.make_response(self.handle_exception(e)) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception reraise(exc_type, exc_value, tb) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise raise value File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1817, in
> wsgi_app response = self.full_dispatch_request() File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request rv = self.handle_user_exception(e) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception reraise(exc_type, exc_value, tb) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise raise value File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request rv = self.dispatch_request() File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/home/khmproject/kcsrv/init.py", line 55, in index return render_template('index.html') File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/templating.py", line 128, in render_template context, ctx.app) File
> "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/templating.py", line 110, in _render rv = template.render(context) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/jinja2/environment.py", line 989, in render return self.environment.handle_exception(exc_info, True) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/jinja2/environment.py", line 754, in handle_exception reraise(exc_type, exc_value, tb) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/jinja2/_compat.py", line 37, in reraise raise value.with_traceback(tb) File "/home/khmproject/kcsrv/templates/index.html", line 2, in top-level template code {% include "layout/_navbar.html" %} File "/home/khmproject/kcsrv/templates/layout/_navbar.html", line 1, in top-level template code {% block navbar %} File "/home/khmproject/kcsrv/templates/layout/_navbar.html", line 21, in block "navbar" {% if not current_user.is_authenticated() %} AttributeError: 'bool' object has no attribute '__call__'
> 127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:16] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /play/ HTTP/1.1" 302 - 127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login HTTP/1.1" 500 - Traceback (most recent call last): File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1836, in __call__
> return self.wsgi_app(environ, start_response) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1820, in wsgi_app response = self.make_response(self.handle_exception(e)) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1403, in handle_exception reraise(exc_type, exc_value, tb) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise raise value File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app response = self.full_dispatch_request() File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request rv = self.handle_user_exception(e) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception reraise(exc_type, exc_value, tb) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise raise value File
> "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request rv = self.dispatch_request() File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "/home/khmproject/kcsrv/lib/python3.4/site-packages/flask_security/decorators.py", line 203, in wrapper if current_user.is_authenticated(): TypeError: 'bool' object is not callable 127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:50] "GET
> /account/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=source.png HTTP/1.1" 200 - 127.0.0.1 - - [20/Sep/2015 23:28:50] "GET /account/login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 - |
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/KanColleTool/kcsrv/issues/27#issuecomment-141792513>.
> 
Oh, this isn't a problem that we can fix on our end, sorry.

You have the following solutions:

 -  Wait until Flask-Security updates.
 -  Downgrade your copy of Flask-Login.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iJ4EARMKAAYFAlX+yYEACgkQbojIu8gUUMb6mAH+N3Qr5VLEOPYnjsNEqhWrjxwa
MwQV/Fx0UaFMjgpcIUiRxaIk5+ExDzAE9tn1wHivNLANO0tH1oJPW9J9S7kF/QIA
pABjgTB6VOYZ26iG1daFizaD06kSp7KvQBkXPTN9Fasu3ixaV9TchyHSQXxD7Yzt
jc1Lt0XezFEA1RKhZqUx5A==
=vBLA
-----END PGP SIGNATURE-----

**Comment by SunDwarf** [comment]
Oh, and see [here](https://github.com/mattupstate/flask-security/issues/416) for more info about this.

**Comment by kdevproject** [comment]
Thank  advice! It's work :)
