### ISSUE TITLE
Change default port to 80

### ISSUE THREAD

**Issue by zhangyubaka** [KanColleTool/kcsrv#28]
I just wonder why don't change port to 80 instead of 5000?

**Comment by SunDwarf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On 20/09/15 20:49, zhangyubaka wrote:
> I just wonder why don't change port to 80 instead of 5000?

You don't put gunicorn on port 80. You put it on an invisible port to the outside world, then have nginx or apache proxy through. Gunicorn is not performant enough, apache2/nginx are, and are also much better at static files, permissions and other important stuff that gunicorn is not.

If you put it forward facing on port 80, I will find you and personally yell at you why your server is going to be rooted.

-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iJ4EARMKAAYFAlX/F8wACgkQbojIu8gUUMYBvAIAqITN4xMajto6lejPogrUli11
yoRYkz5smt871pjsrDA5M5PeBzhxYdXrPHVt4yHZ3qFNpoS1Iju83EIp0ej2AQH/
TmVFtNv//BQp5j7bl+TxLeU1xqONZNGl27rBK6ODhXT5RmteQ8ADXdnI9iWsvIoG
Vd6sShQrHPaKVWwfhqhNvg==
=YKCP
-----END PGP SIGNATURE-----
