### ISSUE TITLE
Game crashes after api_start2 load

### ISSUE THREAD

**Issue by HexSource** [KanColleTool/kcsrv#29]
Hello,
I'm curious about the project and I want to see what it can do. After following the steps on the README, I'm stuck right after the game loads. On the "Game Start" screen, the game crashes (cat girl) exactly after api_start2 finishes loading. The actual game load (blue loading bar) works fine and I even get the "Game Start" button active for a second or so, before the api_start2 request finishes.

I checked the response, and I'm getting "api_result"=1 and "api_result_msg"="\u6210\u529f", so this part seems ok. While I don't know how I would check if the api_data content is correct, it does show a lot of data and is a valid JSON.

After creating an user, I created an Admiral with one fleet and one ship to check if the problem was that I had no flasgship, but this doesn't seem to be related  (or maybe it is? I didn't explicitly set a flagship so I can't tell if I actually have one).

GitHub is not letting me upload the file for whatever reason, but here it's the [full response](https://www.dropbox.com/s/gjpqm1tmgw7mxxj/api_start2_response.txt?dl=0) I'm getting 

I'm not sure what to try now. Do you have any tips?

Thanks for your time!

**Comment by f-matos** [comment]
Oh I read the old Issues, the problem was that the data/api_start2.json file was outdated. I copied the new one from the new DMM site and *apparently* I got past this error and found to the next. Just keep debugging now!

**Comment by SunDwarf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Uh, okay. I assume that means the game has added in some api_start2 check? Fucking hell. Not long until they start checksumming the servers...
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iJ4EARMKAAYFAlYXWNIACgkQbojIu8gUUMaDZAIAj/CJO5GTEzNiSrt+RYmaW4Pe
ntr48YpbCnNuEHr9YJm3dR1BiMZ6pAXq8WPwPjYl6UJ/p22cIYuJp/EgzxtexwH/
VoLPqeOTr3uBw3gIeaN/ZSS2RGZLqvrbcpzxZAS1vhUXnnAjrISXQFpSCsdA5EEk
OFHeL+SQosQweayvd0IAQg==
=SZiS
-----END PGP SIGNATURE-----
