### ISSUE TITLE
Typo in the README.md

### ISSUE THREAD

**Issue by SoftwareGuy** [KanColleTool/kcsrv#31]
Since I'm known to be the local friendly nitpicker, I was looking at the changes to this project you've made, and something stood out at me like a sore thumb:

>Q: What are the requirements?
>
> For a dev environment, nothing more than Vagrant and Ansible are required. These will automatically fire up a

A what? Toaster? Virtual Machine? A shipgirl ready to go to war at the local beach?

~~I are confused.~~ Jokes aside, this is a minor thing but that ~~borken~~ broken line just stood out.

**Comment by SunDwarf** [comment]
Whoops.
