### ISSUE TITLE
Fubuki (starter) is repairing after I got her

### ISSUE THREAD

**Issue by Xaiwaker** [KanColleTool/kcsrv#34]
After getting past the catbomb, I got to my office seeing Fubuki missing until I went to the modernization screen where she was repairing with the docks empty. After I hit the modernization screen and saw that she was repairing, I couldn't see if I could put modernization into her and it started to play some random lines from her. 

Afterwards,  I went to Quests and it catbombed

Note: I am HQ 3 when starting out, 2 fleets, 3 repair docks, and 3 construction slots.

**Comment by SunDwarf** [comment]
Oh, that's a nice new bug.

Could you capture the api_port response generated? To see what's going on.

**Comment by Xaiwaker** [comment]
Where do I find that?

I read that quests and most buttons on top lead to catbombs so my bad on that.

**Comment by SunDwarf** [comment]
In your network tab on the dev menu, there should be an /api_port/port request.

**Comment by Xaiwaker** [comment]
Would this work? 
http://prntscr.com/9utfag

**Comment by SunDwarf** [comment]
It'd be a lot better if you could copy the data in the Response tab here.

**Comment by Xaiwaker** [comment]
svdata={"api_result":1,"api_data":{"api_combined_flag":0,"api_basic":{"api_comment_id":"","api_pt_challenged_win":0,"api_large_dock":0,"api_max_slotitem":10000,"api_comment":"","api_pvp":[0,0],"api_active_flag":1,"api_max_kagu":10000,"api_ms_count":0,"api_fcoin":0,"api_count_kdock":3,"api_max_chara":5000,"api_pt_win":0,"api_pt_lose":0,"api_pt_challenged":0,"api_count_deck":2,"api_nickname":"Dechi","api_fleetname":null,"api_experience":200,"api_tutorial":0,"api_medals":0,"api_rank":8,"api_ms_success":0,"api_nickname_id":15,"api_st_win":0,"api_firstflag":1,"api_level":3,"api_playtime":0,"api_st_lose":0,"api_furniture":[1,1,1,1,1,1],"api_member_id":8,"api_starttime":1430603452688,"api_count_ndock":3,"api_tutorial_progress":100},"api_parallel_quest_count":10,"api_log":[{"api_type":"1","api_no":0,"api_state":"0","api_message":"It's a beautiful day outside."},{"api_type":"1","api_no":1,"api_state":"0","api_message":"Birds are singing. Flowers are blooming."},{"api_type":"1","api_no":2,"api_state":"0","api_message":"On days like these, kids like you..."},{"api_type":"1","api_no":3,"api_state":"0","api_message":"\uff33\uff48\uff4f\uff55\uff4c\uff44\u00a0 \uff42\uff45\u00a0 \uff42\uff55\uff52\uff4e\uff49\uff4e\uff47\u00a0 \uff49\uff4e\u00a0 \uff48\uff45\uff4c\uff4c\uff0e"}],"api_ndock":[{"api_item3":null,"api_state":0,"api_item2":null,"api_item1":null,"api_member_id":8,"api_id":1,"api_created_ship_id":0,"api_item5":null,"api_complete_time_str":"","api_complete_time":null,"api_item4":null},{"api_item3":null,"api_state":0,"api_item2":null,"api_item1":null,"api_member_id":8,"api_id":2,"api_created_ship_id":0,"api_item5":null,"api_complete_time_str":"","api_complete_time":null,"api_item4":null},{"api_item3":null,"api_state":0,"api_item2":null,"api_item1":null,"api_member_id":8,"api_id":3,"api_created_ship_id":0,"api_item5":null,"api_complete_time_str":"","api_complete_time":null,"api_item4":null},{"api_item3":0,"api_state":-1,"api_item2":0,"api_item1":0,"api_member_id":8,"api_id":4,"api_created_ship_id":0,"api_item5":0,"api_complete_time_str":"","api_complete_time":0,"api_item4":0}],"api_p_bgm_id":100,"api_deck_port":[{"api_name":"Unnamed","api_mission":[0,0,0,0],"api_name_id":"","api_member_id":8,"api_id":1,"api_flagship":0,"api_ship":[0,-1,-1,-1,-1,-1]},{"api_name":"Unnamed","api_mission":[0,0,0,0],"api_name_id":"","api_member_id":8,"api_id":2,"api_flagship":0,"api_ship":[-1,-1,-1,-1,-1,-1]}],"api_ship":[{"api_onslot":[0,0,0,0,0],"api_raisou":[27,79],"api_slotnum":2,"api_nowhp":15,"api_locked_equip":0,"api_lv":1,"api_taiku":[10,39],"api_id":0,"api_soukou":[5,19],"api_backs":3,"api_karyoku":[10,29],"api_kaihi":[0,0],"api_cond":49,"api_ndock_item":[0,0],"api_locked":false,"api_bull":20,"api_lucky":[17,49],"api_exp":[0,100,0],"api_sortno":11,"api_sakuteki":[0,0],"api_ndock_time":0,"api_maxhp":15,"api_sally_area":0,"api_srate":1,"api_slot":[-1,-1],"api_taisen":[0,0],"api_leng":1,"api_fuel":15,"api_ship_id":9,"api_kyouka":[0,0,0,0,0]}],"api_material":[{"api_id":1,"api_value":773,"api_member_id":8},{"api_id":2,"api_value":773,"api_member_id":8},{"api_id":3,"api_value":773,"api_member_id":8},{"api_id":4,"api_value":682,"api_member_id":8},{"api_id":5,"api_value":3,"api_member_id":8},{"api_id":6,"api_value":4,"api_member_id":8},{"api_id":7,"api_value":5,"api_member_id":8},{"api_id":8,"api_value":1,"api_member_id":8}]},"api_result_msg":"\u6210\u529f"}
