### ISSUE TITLE
ImportError: No module named 'flask.ext'

### ISSUE THREAD

**Issue by shirakun** [KanColleTool/kcsrv#37]
```
chdir=/vagrant /usr/bin/python3.5 /vagrant/manage.py db u
pgrade
Traceback (most recent call last):
  File "/vagrant/manage.py", line 4, in <module>
    from flask.ext.migrate import Migrate, MigrateCommand
ImportError: No module named 'flask.ext'

```

When I started the vagrant startup, I found the VBox file 404

I changed it to ubuntu16

But there is no command to run playhook after VM starts

I install it manually

I met this mistake

How to solve it?

**Comment by Fuyukai** [comment]
This repo has been dead for ~2 years. Install an old version of Flask.

**Comment by shirakun** [comment]
@Fuyukai Available Flask version number?

**Comment by Fuyukai** [comment]
Fuck if I know.
