### ISSUE TITLE
Stuck at Loading screen

### ISSUE THREAD

**Issue by zhangyubaka** [KanColleTool/kcsrv#4]
Stuck at Loading screen

**Comment by SoftwareGuy** [comment]
A lot of stuff is broken. There's 1 main dev and a float-in-float-out dev (that's me) although I have been able to get it to boot to the title screen.

**Comment by uppfinnarn** [comment]
It's terribly incomplete and under development. Do feel free to help out, but don't expect it to be usable for quite a while.
