### ISSUE TITLE
Can't login the web page after execute kcsrv.py

### ISSUE THREAD

**Issue by OkazakiNaoki** [KanColleTool/kcsrv#7]
Hello there, after I finished the step of setup environment and faced really much problem.
I click the login and type the email address and password which I just created with manage.py.
However, it just turn red and won't let me login...
![123](https://cloud.githubusercontent.com/assets/11442114/6651450/7710a400-ca7d-11e4-8aff-7b8fa7b1dc9b.png)

I'm sure I created my account successfully.

Thank you if this could be resolved and thank you for create this project !
I also like to learn something from you, I never seen vagrant and ansible before.
This really take me times.
Only tried mysql and perl basiclly :)

**Comment by SoftwareGuy** [comment]
Hmmm... That's odd.

Can you please try making a generic dummy account like user@user.com with a password like kancolle (all lowercase for sanity sake) and see if that logs in? Otherwise something is not quite right with the setup. Have you created the database?

**Comment by OkazakiNaoki** [comment]
what database? I'm only follow the setup step.
Am I need to install postgreSQL and create a user?
If not I actually did all the step and without any error(took me all night), actually I think what I did may similar to yours.

I installed it on VM run by CentOS 6.6 32-bit, and modify vagrant config to trusty32 or else "vagrant up" will failed because 64-bit version of ubuntu startup was too slow to wait. Then use ubuntu built-in Python2 to run ./manage.py then final execute kcsrv.py.

Or maybe I should run it on ubuntu 64-bit?

**Comment by SoftwareGuy** [comment]
Wait... Are you running a VM inside a VM? That's suicide, really...
There is ansible and vagrant available for Windows. You may want to use that.

I guess the other option is to use a spare PC as a Linux VM host but that means you have to have a spare PC.

**Comment by uppfinnarn** [comment]
Like I've said like three times this month already (sorry if I sound tired of repeating it), this is not production ready. It's not usable. It will not play the game yet. If you want to help develop it, go right ahead. I'm too swamped with work and an important project to develop it right now, but I will gladly answer questions.

That said, yes, running a VM inside a VM is a terrible idea, although enabling virtualized VT-X should help if you really want to. Running 32bit anything in 2015, however, is not a particularly good idea.

I realized only about a week ago that Ansible does not officially support Windows (although it'll apparently work anyways?), and I might change the provisioning to use Puppet instead for this exact reason - Puppet works entirely on-VM, so the host OS doesn't matter.

**Comment by OkazakiNaoki** [comment]
I did enabled virtualized VT-X but if VM in VM isn't a good idea then I'll just remove it.
Anything I can do for this project? Don't know what knowledge is actually needed.
I got times to learn because I'm still a student and also really interested in game server build.

p.s. What kind of work content make you so busy? May I ask about it, just feel curious about what CS field job like?

**Comment by uppfinnarn** [comment]
Take a look around, intercept game traffic and implement endpoints that mimic it. The framework currently used is [Flask](http://flask.pocoo.org/), but I'm open to move it to [Django](http://djangoproject.com/) if people are more comfortable with that.

Right now, I've for the moment essentially ended up being an entire department on my own, and my limited free time is currently occupied with filling a more immediate need for my FFXIV FC. Can't say too much about either though, for different reasons.
Full-time work as a developer is fun though, definitely recommended, if you can find someplace that will hire you that isn't promoting cancer/unironically using PHP/ignoring needs for profit/all the other bs like 99% of places around here pull. (Swallowing some cancer could be worth it to get references though)

**Comment by SoftwareGuy** [comment]
I probably should open source my server code (which uses PHP, same what DMM uses themselves) as my implementation is currently able to get you to your desktop/dashboard/the scene with your secretary ship. Reverse Engineering ftw!

If you're interested, do check my own repo and watch that - not trying to derail this project, but I can forsee us using some of my API implementations/logic/etc in the python version.

**Comment by OkazakiNaoki** [comment]
A project build by PHP plus MySQL will be good for me. But also interested in Python, I love the structure of it, so simple. 
Sure, I'm interested in your project. What kind of sniffer program you use to catch KanColle packet?

I didn't tried sniffer before just know really a little about pcap.
I found some article like this : 
http://hellotim.me/2014/12/13/intercepting-analyzing-puzzle-and-dragons-traffic/

Although it's mobile game, but it still web-based right? Is it what are we doing?
Forgive me my poor knowledge because I'm a noob who still leaning now.

**Comment by SoftwareGuy** [comment]
I used Wireshark, with an IP filter. It's a little tricky, but allows you to see what your machine is POSTing to the server and the response. For quick "how do they do that?" I just boot the game up in Chrome and pop open the Network Resource viewer and watch the requests going in and out.

**Comment by OkazakiNaoki** [comment]
I didn't have an account of KanColle yet.
I'm going to have one on 3/24 if lucky enough.

And I found that if we mimic the original code by playing and sniffing packet at the same time.
Then what we gonna deal with the pay to unlock? Paid then sniff?
And hold an event by our self, that's a lot of problems.

**Comment by uppfinnarn** [comment]
Dissect the SWFs? I dunno

**Comment by SoftwareGuy** [comment]
Never try holding events with stuff that is copyrighted by others unless we have permission. (but fuck EULAs, who reads them anyway). Unless we take KanColle, hire a few dozen artists, and code our own ship game then there's no problem.

Paid content is easily "unlocked" by changing a few params in the API response data.

There's a value, which you can see called api_docks or api_kdocks which should be '2' if you're just a new admiral. On mine, I have 3 open.

Since the pay to unlock stuff trigger a DMM popup, I simply hard code how many fleets you have and construction/repair docks to 4. This makes the game unlock all the docks and stuff. So when you register, I set the docks open value to 4 in the database and you can do LSC right off the bat too when you get into the game.

**Comment by SoftwareGuy** [comment]
@OkazakiNaoki If you happen to get past the DMM lottery, can you please send me an email - the email is in my profile. I may need some clean DMM responses for various API nodes, I'm currently looking into equipment. Otherwise I'd have to make a dupe account on DMM and I'm not sure if they would just connect the dots and ban.

**Comment by OkazakiNaoki** [comment]
I send the email and it seems return to me because it's a noreply mail address.
I see this one : SoftwareGuy@users.noreply.github.com
Is this the right one?

**Comment by SoftwareGuy** [comment]
@OkazakiNaoki That's correct.

**Comment by SoftwareGuy** [comment]
Just saw that the API has been updated and not sure if that will break any implementations for our custom servers... I wonder when did the API change...

I've said this before, the API is a horrible mess. I have implemented ship creation, but the thing is, where do I source the ship's gear from? Do I need to source the unofficial wikia for KC and build a dataset with all the items? 

Maybe I need to open another issue and use that as a discussion board-like thing so even if you aren't a developer you can still weigh in on things...

Still, as a spare-time challenge, this reverse engineering is quite a pain in the butt at times... I wish I knew what half the API fields meant (some are firepower, etc) but I don't know what the others do.

**Comment by OkazakiNaoki** [comment]
Can you give me some tutorial about sniff or some direction to searching on Google?
I don't really know where to start.
Without any experience before, need a little guide.

**Comment by SoftwareGuy** [comment]
It's rather easy to do with Chrome's network viewer. Firefox can do it too AFAIK.

To make it easier, set your Flash plugin to be "click to run". This will stop Flash applets from auto-running, allowing you to control when the game starts.

Go to the DMM website and do the usual routine to login. When you're on the game's page with the 800x480 game client window and the 5 or so buttons, press F12 (if you're on Windows) or use the respective "Web Console" command in the menus if you're on OS X or Linux. You'll get a panel either to the right of the browser, or down the bottom. Click "Network" on the inspector. This will open a panel with Name, Method, Status, Type and friends. Click the area where KanColle is (should be grey with "Click to run Adobe Flash Player" on it). The ship will appear, and in the window, you'll see entries, like api_start2 and such. This is your browser talking to DMM's server and it's feeding the game back JSON encoded data.

Clicking on any of the entries in the network log will show additional information about that entry. Some of it will go over the top of your head. If you look closely, you'll see a "headers" text area that shows what the game sent to the server. Usually, it's your API token plus the version of the API (1.0) but sometimes when you're playing the game you'll get requests that have additional info, like for example when you make a ship, it will send how many resources you used and the server will reply with the ship the RNG granted you.

What I need in particular, is the data from the "useitem", "slot_item" and "unsetslot" API endpoints. Click on those entries in the list and then from the little inspector that appears, click "Response". Copy that text that appears as that's what we want, and then paste it into a Gist here (gist.github.com I think?) so we can see what the new accounts get in those API endpoints.

Also, as a protip, if you see anything with "api_token" in the response, never give the 40 character string to anyone. That token is like your session and stays the same unless you log out of DMM and log back in. In my experience, there's no responses that reply with the api_token, the client only uses it to POST to the server.

I know this is making your head spin but hopefully I've explained it somewhat.
