### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by SunDwarf** [KanColleTool/kcsrv#8]
So, I've forked this and got the basic login handshake working (minutes before I broke it again), and I want to slap a licence on it.  
Only problem is, I don't own the code, @uppfinnarn does.  
Any chance of getting something like MIT/BSD on it?

**Comment by uppfinnarn** [comment]
Oshit, I forgot to put in a license file - lemme put that in real quick...

**Comment by SunDwarf** [comment]
Speedy, thanks!

**Comment by SoftwareGuy** [comment]
Sorry to reopen but @SunDwarf you might find my [server repo](https://github.com/SoftwareGuy/kantcollesrv) handy to get the basic things down pat. Mine's PHP but I've thrown in the towel with my own server project. Don't have the time or energy to do that right now.
